name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**/compose.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Deploy (Using Tailscale SSH)
        run: |
          ssh -o "StrictHostKeyChecking no" bot-containers@dev-m1sk9-ubuntu-001 "
            ./deploy.sh
          "
