name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**/compose.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }} 

      - name: Deploy (Using Tailscale SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd apps
            git pull origin main
            find . -name compose.yaml -type f -maxdepth 2 -print0 | while IFS= read -r -d '' compose_file; do
              workdir=$(dirname "$compose_file")
              cd "$workdir"

              docker compose up -d --build

              cd -
            done
